---
- name: Vérifier si K3s est déjà installé
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Installer K3s en tant qu'agent (worker), rejoignant le nœud maître
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io |
    K3S_URL="https://{{ hostvars[groups['k3s_master'][0]]['private_ip'] }}:6443"
    K3S_TOKEN="{{ hostvars[groups['k3s_master'][0]]['k3s_join_token'] }}"
    INSTALL_K3S_EXEC="--node-ip={{ private_ip }} --flannel-iface=eth1"
    sh -
  when: not k3s_binary.stat.exists
  environment:
    INSTALL_K3S_VERSION: "v1.30.5+k3s1"

- name: S'assurer que le service K3s agent est démarré et activé au boot
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    enabled: true